### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version "^18". Got "20.13.1"

### ISSUE THREAD

**Issue by mcbain** [matthiasfeist/geojson-minimum-bounding-rectangle#14]
IMO the correct usage is

`"engines": {
  "node": ">=18"
}`

**Comment by matthiasfeist** [comment]
good catch. I'll fix the package!

**Comment by matthiasfeist** [comment]
@mcbain I just published a new version to NPM (v2.0.2) with the fix.
